import os
import pathlib
import sqlite3

DATABASE_DIR = pathlib.Path(__file__).parent.parent / "database"
SCHEMA_PATH = DATABASE_DIR / "schema_sqlite.sql"
SCHEMA_POSTGRES_PATH = DATABASE_DIR / "schema_postgres.sql"


def get_engine():
    return os.environ.get("DB_ENGINE", "sqlite").lower()


def format_query(sql_string):
    """Rewrites sqlite-style '?' placeholders to psycopg2-style '%s' when the
    active engine is PostgreSQL, so services can keep writing one SQL string.
    """
    if get_engine() == "postgresql":
        return sql_string.replace("?", "%s")
    return sql_string


def get_connection(path):
    if get_engine() == "postgresql":
        import psycopg2

        return psycopg2.connect(os.environ["DATABASE_URL"])
    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def get_last_row_id(cursor, table_name, id_column="id"):
    """Returns the id generated by the row just inserted through `cursor`.

    sqlite3 exposes this directly as cursor.lastrowid. psycopg2 has no such
    attribute -- SERIAL columns advance a per-session sequence on INSERT, so
    currval(pg_get_serial_sequence(...)) recovers the same value without
    requiring every INSERT string to carry its own RETURNING clause.
    """
    if get_engine() == "postgresql":
        cursor.execute(
            "SELECT currval(pg_get_serial_sequence(%s, %s))",
            (table_name, id_column),
        )
        return cursor.fetchone()[0]
    return cursor.lastrowid


def integrity_errors():
    """Returns the exception class(es) that signal a constraint violation
    (e.g. a FOREIGN KEY RESTRICT) for whichever engine is active, so routes
    can catch a delete/insert conflict without importing psycopg2 directly
    -- psycopg2 is only installed/importable when DB_ENGINE=postgresql.
    """
    if get_engine() == "postgresql":
        import psycopg2

        return (psycopg2.IntegrityError,)
    return (sqlite3.IntegrityError,)


def init_db(conn):
    if get_engine() == "postgresql":
        with conn.cursor() as cursor:
            cursor.execute(SCHEMA_POSTGRES_PATH.read_text())
        conn.commit()
    else:
        conn.executescript(SCHEMA_PATH.read_text())
